services:

  redis-master:
    container_name: redis-master
    image:  redis:5.0
    restart: "always"
    ports:
      - 6379:6379
    volumes:
      - ./app/redis/conf/redis.conf:/etc/redis/redis.conf
      - /app/redis/data:/data
    networks:
      - hack
    command: redis-server /etc/redis/redis.conf
    
  mysql:
    image: mysql:5.7
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - /app/mysql/data:/var/lib/mysql/
      - /app/mysql/conf:/etc/mysql/conf.d
      - /app/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=13032637048
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=stu_manage_gitee
    networks:
      - hack
    command: --default-authentication-plugin=mysql_native_password

  admin:
    restart: "always"
    depends_on:
      - mysql
    build:
      context: stu3/
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - hack
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=13032637048
  
networks:
  hack:
 
 

























































































 
  